### ISSUE TITLE
You don't have to write the html twice for desktop and mobile

### ISSUE THREAD

**Issue by farishkash** [Knightwolfbr/f1-3-c2p1-colmar-academy#2]
The idea with media queries is to do enough changes with css that you alter the structure the site without writing it twice.

Through targeting you can make structural switches using css without that extra work.

This is a little codepen is an example of that.

https://codepen.io/Farish/pen/gGWwoK

The html is written once only but when the media query hits it shifts completely.  This will help your efficiency so you aren't doubling up in code.

**Comment by Knightwolfbr** [comment]
Thank you. I realized when I was almost done that I should have written all of the required html first (instead of in the media queries) and then used those to change things that I needed.
