### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [Knightwolfbr/f1-3-c2p1-colmar-academy#3]
Overall excellent.

This project didn't have any major errors or issues.

Very clean code formatting.

Good organizational practices with comments in your html and css file.

Alt text is important and I wish it was discussed more in our course.
When it comes to media queries and double html.  I would say half the projects I review approach this the same way as you did.  My goal is to stop that habit now and set everybody on a better path.

Since you just finished off with flexbox I like to mention css grids.
CSS grids is a new positioning feature that works with flexbox.

They will be fully supported by browsers soon.

Take a look at this game and see how far you can get to help prepare you for them.

http://cssgridgarden.com/

Also if you haven't done so already we added css grid as the last section of our css course now.

https://www.codecademy.com/learn/learn-css

Maybe as a final challenge see if you can incorporate it into this site.

**Comment by Knightwolfbr** [comment]
Yes I saw the CSS Grid course but it wasn't included in this particular course. I will take that course after I finish up the last week here. Thank you!
